version: "3.8"

services:
  api:
    build: .
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5555"]
    ports:
      - "5555:5555"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/mydb"
      SECRET_KEY: jidasjidasijdasiddasd
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_IN_MINUTES: 30
    restart: always

  db:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "mydb"
    volumes:
      - "./sql_data:/var/lib/postgresql/data"
